//To check all available fonts, press command or control + click on the name of the font, and it will take you to the index.d.ts file where there is a list of available fonts

//import the font
import { Roboto_Mono } from "next/font/google";

import "./globals.css";
//we need to configure our font with different properties
const roboto = Roboto_Mono({ weight: "500", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* apply the font */}
      <body className={roboto.className}>{children}</body>
    </html>
  );
}

//you can also use fonts locally stored
