//the layout component is the blueprint for my pages.
//if the layout is the app folder, it will apply to ALL pages.
//you can also have layout components in your route folders, if you want a different bluepring for a particular page.
import Header from "@/components/Header";
// import Footer from "./src/components/Footer";
import Footer from "@/components/Footer";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//the parameter children represents each individual page component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
